# These are supported funding model platforms

github: [yourusername] # Replace with your GitHub username
# ko_fi: yourusername # Replace with your Ko-fi username
# open_collective: yourusername # Replace with your Open Collective username
# patreon: yourusername # Replace with your Patreon username
# tidelift: yourusername # Replace with your Tidelift username
# community_bridge: yourusername # Replace with your Community Bridge username
# liberapay: yourusername # Replace with your Liberapay username
# issuehunt: yourusername # Replace with your IssueHunt username
# otechie: yourusername # Replace with your Otechie username
# custom: ["https://your-custom-link.com"] # Replace with your custom link
