# GitHub Labels configuration
# https://github.com/actions/labeler

labels:
  # Типы изменений
  - name: "bug"
    color: "d73a4a"
    description: "Что-то не работает"
  - name: "enhancement"
    color: "a2eeef"
    description: "Новая функция или запрос"
  - name: "documentation"
    color: "0075ca"
    description: "Улучшения или дополнения к документации"
  - name: "good first issue"
    color: "7057ff"
    description: "Хорошая задача для новичков"
  - name: "help wanted"
    color: "008672"
    description: "Нужна помощь с этой задачей"
  - name: "invalid"
    color: "e4e669"
    description: "Что-то не так с этим issue"
  - name: "question"
    color: "d876e3"
    description: "Дополнительная информация запрошена"
  - name: "wontfix"
    color: "ffffff"
    description: "Это не будет исправлено"

  # Приоритеты
  - name: "priority: high"
    color: "ff0000"
    description: "Высокий приоритет"
  - name: "priority: medium"
    color: "ffa500"
    description: "Средний приоритет"
  - name: "priority: low"
    color: "ffff00"
    description: "Низкий приоритет"

  # Компоненты
  - name: "component: ui"
    color: "c2e0c6"
    description: "Изменения в пользовательском интерфейсе"
  - name: "component: map"
    color: "c2e0c6"
    description: "Изменения в интерактивной карте"
  - name: "component: characters"
    color: "c2e0c6"
    description: "Изменения в разделе персонажей"
  - name: "component: gallery"
    color: "c2e0c6"
    description: "Изменения в галерее"
  - name: "component: animations"
    color: "c2e0c6"
    description: "Изменения в анимациях"

  # Статус
  - name: "status: in progress"
    color: "1d76db"
    description: "Работа в процессе"
  - name: "status: blocked"
    color: "ff0000"
    description: "Заблокировано"
  - name: "status: ready for review"
    color: "0e8a16"
    description: "Готово к проверке"
  - name: "status: needs review"
    color: "fbca04"
    description: "Требует проверки"

  # Автоматизация
  - name: "automated"
    color: "d4c5f9"
    description: "Автоматически создано"
  - name: "dependencies"
    color: "0366d6"
    description: "Обновления зависимостей"
  - name: "github-actions"
    color: "0366d6"
    description: "GitHub Actions"
  - name: "security"
    color: "ff0000"
    description: "Проблемы безопасности"

  # Размер
  - name: "size: xs"
    color: "9c9c9c"
    description: "Очень маленькое изменение"
  - name: "size: s"
    color: "44aaff"
    description: "Маленькое изменение"
  - name: "size: m"
    color: "ffaa44"
    description: "Среднее изменение"
  - name: "size: l"
    color: "ff4444"
    description: "Большое изменение"
  - name: "size: xl"
    color: "cc0000"
    description: "Очень большое изменение"
