blank_issues_enabled: false
contact_links:
  - name: 🆘 Нужна помощь?
    url: https://github.com/yourusername/krasnotsarstvo-exe-site/discussions
    about: Задайте вопрос в Discussions
  - name: 📚 Документация
    url: https://github.com/yourusername/krasnotsarstvo-exe-site#readme
    about: Прочитайте README для получения дополнительной информации
  - name: 💬 Чат команды
    url: https://t.me/lib_rzhevka
    about: Telegram канал команды
